name       : parted
version    : 3.2
release    : 5
source     :
    - https://ftp.gnu.org/gnu/parted/parted-3.2.tar.xz : 858b589c22297cacdf437f3baff6f04b333087521ab274f7ab677cb8c6bb78e4
license    : GPL-3.0-or-later
component  :
    - system.utils
    - ^libparted-devel : programming.devel
    - ^libparted : programming.library
summary    :
    - Disk partitioning and partition resizing tool
    - ^libparted-devel : Development files for libparted
    - ^libparted : Disk partitioning and partition resizing tool - shared libraries
description: |
    GNU Parted manipulates partition tables. This is useful for creating space for new operating systems, reorganizing disk usage, copying data on hard disks and disk imaging.
patterns   :
    - ^libparted-devel :
        - /usr/include/parted/*.h
        - /usr/lib64/libp*.so
        - /usr/lib64/pkgconfig
    - ^libparted :
        - /usr/sbin/partprobe
        - /usr/share/locale
        - /usr/share/man/man8/partprobe.8
        - /usr/lib64/lib*.so.*
builddeps  :
    - pkgconfig(lvm2app)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
