name       : parted
version    : '3.6'
release    : 10
source     :
    - https://ftp.gnu.org/gnu/parted/parted-3.6.tar.xz : 3b43dbe33cca0f9a18601ebab56b7852b128ec1a3df3a9b30ccde5e73359e612
license    : GPL-3.0-or-later
component  :
    - system.utils
    - ^libparted-devel : programming.devel
    - ^libparted : programming.library
summary    :
    - Disk partitioning and partition resizing tool
    - ^libparted-devel : Development files for libparted
    - ^libparted : Disk partitioning and partition resizing tool - shared libraries
description: |
    GNU Parted manipulates partition tables. This is useful for creating space for new operating systems, reorganizing disk usage, copying data on hard disks and disk imaging.
patterns   :
    - ^libparted-devel :
        - /usr/include/parted/*.h
        - /usr/lib64/libp*.so
        - /usr/lib64/pkgconfig
    - ^libparted :
        - /usr/sbin/partprobe
        - /usr/share/locale
        - /usr/share/man/man8/partprobe.8
        - /usr/lib64/lib*.so.*
builddeps  :
    - pkgconfig(devmapper)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
